name: NeuroSync
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - audioread==3.0.1
      - blinker==1.9.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.0
      - decorator==5.2.1
      - filelock==3.13.1
      - flask==3.1.0
      - fsspec==2024.6.1
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.5.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.3
      - numba==0.61.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==25.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - pycparser==2.22
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - triton==3.2.0
      - typing-extensions==4.12.2
      - urllib3==2.4.0
      - werkzeug==3.1.3
